package model;
// Generated Mar 17, 2011 11:07:55 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="dbpaathshala"
)
public class Student  implements java.io.Serializable {


     private Integer idstudent;
     private Student studentByIdsibling3;
     private Student studentByIdsibling2;
     private Student studentByIdsibling1;
     private String scholarno;
     private String formnumber;
     private Date admissiondateschool;
     private Date admissiondateclass;
     private String enrollmentno;
     private String examrollno;
     private String classrollno;
     private String firstname;
     private String middlename;
     private String lastname;
     private Integer idfather;
     private Integer idmother;
     private Integer idgd1;
     private Integer idgd2;
     private int idfeedivision;
     private Integer idfeediscountgp;
     private Integer idedusection;
     private Integer idedusemester;
     private Date dob;
     private String pob;
     private Double previousyearfeedues;
     private String previousschoolscholarno;
     private String previousschool;
     private String previousclass;
     private String previousresult;
     private String previousdivision;
     private Double previouspercentage;
     private String reasonofleaving;
     private Integer idmothertongue;
     private String email;
     private String praddrhouseno;
     private String praddrstreet;
     private Integer praddrarea;
     private Integer praddrcity;
     private Integer praddrstate;
     private Integer praddrpin;
     private String pmaddrhouseno;
     private String pmaddrstreet;
     private Integer pmaddrarea;
     private Integer pmaddrcity;
     private Integer pmaddrstate;
     private Integer pmaddrpin;
     private String nationality;
     private Double weight;
     private Double height;
     private String bloodgp;
     private String phydisab;
     private Integer idcategory;
     private Integer idreligion;
     private Integer idcaste;
     private String gender;
     private Integer nobrothers;
     private Integer nosisters;
     private String shift;
     private String idstaff;
     private String staffname;
     private String staffdesig;
     private byte[] photo;
     private Long contactno;
     private Integer idhostelbed;
     private Integer idvehiclearea;
     private Integer deltag;
     private Integer idacademicsession;
     private Set<Student> studentsForIdsibling3 = new HashSet<Student>(0);
     private Set<Student> studentsForIdsibling1 = new HashSet<Student>(0);
     private Set<Student> studentsForIdsibling2 = new HashSet<Student>(0);

    public Student() {
    }

	
    public Student(String scholarno, String formnumber, String firstname, String lastname, int idfeedivision, String gender) {
        this.scholarno = scholarno;
        this.formnumber = formnumber;
        this.firstname = firstname;
        this.lastname = lastname;
        this.idfeedivision = idfeedivision;
        this.gender = gender;
    }
    public Student(Student studentByIdsibling3, Student studentByIdsibling2, Student studentByIdsibling1, String scholarno, String formnumber, Date admissiondateschool, Date admissiondateclass, String enrollmentno, String examrollno, String classrollno, String firstname, String middlename, String lastname, Integer idfather, Integer idmother, Integer idgd1, Integer idgd2, int idfeedivision, Integer idfeediscountgp, Integer idedusection, Integer idedusemester, Date dob, String pob, Double previousyearfeedues, String previousschoolscholarno, String previousschool, String previousclass, String previousresult, String previousdivision, Double previouspercentage, String reasonofleaving, Integer idmothertongue, String email, String praddrhouseno, String praddrstreet, Integer praddrarea, Integer praddrcity, Integer praddrstate, Integer praddrpin, String pmaddrhouseno, String pmaddrstreet, Integer pmaddrarea, Integer pmaddrcity, Integer pmaddrstate, Integer pmaddrpin, String nationality, Double weight, Double height, String bloodgp, String phydisab, Integer idcategory, Integer idreligion, Integer idcaste, String gender, Integer nobrothers, Integer nosisters, String shift, String idstaff, String staffname, String staffdesig, byte[] photo, Long contactno, Integer idhostelbed, Integer idvehiclearea, Integer deltag, Integer idacademicsession, Set<Student> studentsForIdsibling3, Set<Student> studentsForIdsibling1, Set<Student> studentsForIdsibling2) {
       this.studentByIdsibling3 = studentByIdsibling3;
       this.studentByIdsibling2 = studentByIdsibling2;
       this.studentByIdsibling1 = studentByIdsibling1;
       this.scholarno = scholarno;
       this.formnumber = formnumber;
       this.admissiondateschool = admissiondateschool;
       this.admissiondateclass = admissiondateclass;
       this.enrollmentno = enrollmentno;
       this.examrollno = examrollno;
       this.classrollno = classrollno;
       this.firstname = firstname;
       this.middlename = middlename;
       this.lastname = lastname;
       this.idfather = idfather;
       this.idmother = idmother;
       this.idgd1 = idgd1;
       this.idgd2 = idgd2;
       this.idfeedivision = idfeedivision;
       this.idfeediscountgp = idfeediscountgp;
       this.idedusection = idedusection;
       this.idedusemester = idedusemester;
       this.dob = dob;
       this.pob = pob;
       this.previousyearfeedues = previousyearfeedues;
       this.previousschoolscholarno = previousschoolscholarno;
       this.previousschool = previousschool;
       this.previousclass = previousclass;
       this.previousresult = previousresult;
       this.previousdivision = previousdivision;
       this.previouspercentage = previouspercentage;
       this.reasonofleaving = reasonofleaving;
       this.idmothertongue = idmothertongue;
       this.email = email;
       this.praddrhouseno = praddrhouseno;
       this.praddrstreet = praddrstreet;
       this.praddrarea = praddrarea;
       this.praddrcity = praddrcity;
       this.praddrstate = praddrstate;
       this.praddrpin = praddrpin;
       this.pmaddrhouseno = pmaddrhouseno;
       this.pmaddrstreet = pmaddrstreet;
       this.pmaddrarea = pmaddrarea;
       this.pmaddrcity = pmaddrcity;
       this.pmaddrstate = pmaddrstate;
       this.pmaddrpin = pmaddrpin;
       this.nationality = nationality;
       this.weight = weight;
       this.height = height;
       this.bloodgp = bloodgp;
       this.phydisab = phydisab;
       this.idcategory = idcategory;
       this.idreligion = idreligion;
       this.idcaste = idcaste;
       this.gender = gender;
       this.nobrothers = nobrothers;
       this.nosisters = nosisters;
       this.shift = shift;
       this.idstaff = idstaff;
       this.staffname = staffname;
       this.staffdesig = staffdesig;
       this.photo = photo;
       this.contactno = contactno;
       this.idhostelbed = idhostelbed;
       this.idvehiclearea = idvehiclearea;
       this.deltag = deltag;
       this.idacademicsession = idacademicsession;
       this.studentsForIdsibling3 = studentsForIdsibling3;
       this.studentsForIdsibling1 = studentsForIdsibling1;
       this.studentsForIdsibling2 = studentsForIdsibling2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idstudent", unique=true, nullable=false)
    public Integer getIdstudent() {
        return this.idstudent;
    }
    
    public void setIdstudent(Integer idstudent) {
        this.idstudent = idstudent;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsibling3")
    public Student getStudentByIdsibling3() {
        return this.studentByIdsibling3;
    }
    
    public void setStudentByIdsibling3(Student studentByIdsibling3) {
        this.studentByIdsibling3 = studentByIdsibling3;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsibling2")
    public Student getStudentByIdsibling2() {
        return this.studentByIdsibling2;
    }
    
    public void setStudentByIdsibling2(Student studentByIdsibling2) {
        this.studentByIdsibling2 = studentByIdsibling2;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsibling1")
    public Student getStudentByIdsibling1() {
        return this.studentByIdsibling1;
    }
    
    public void setStudentByIdsibling1(Student studentByIdsibling1) {
        this.studentByIdsibling1 = studentByIdsibling1;
    }
    
    @Column(name="scholarno", nullable=false, length=15)
    public String getScholarno() {
        return this.scholarno;
    }
    
    public void setScholarno(String scholarno) {
        this.scholarno = scholarno;
    }
    
    @Column(name="formnumber", nullable=false, length=25)
    public String getFormnumber() {
        return this.formnumber;
    }
    
    public void setFormnumber(String formnumber) {
        this.formnumber = formnumber;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="admissiondateschool", length=10)
    public Date getAdmissiondateschool() {
        return this.admissiondateschool;
    }
    
    public void setAdmissiondateschool(Date admissiondateschool) {
        this.admissiondateschool = admissiondateschool;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="admissiondateclass", length=10)
    public Date getAdmissiondateclass() {
        return this.admissiondateclass;
    }
    
    public void setAdmissiondateclass(Date admissiondateclass) {
        this.admissiondateclass = admissiondateclass;
    }
    
    @Column(name="enrollmentno", length=15)
    public String getEnrollmentno() {
        return this.enrollmentno;
    }
    
    public void setEnrollmentno(String enrollmentno) {
        this.enrollmentno = enrollmentno;
    }
    
    @Column(name="examrollno", length=15)
    public String getExamrollno() {
        return this.examrollno;
    }
    
    public void setExamrollno(String examrollno) {
        this.examrollno = examrollno;
    }
    
    @Column(name="classrollno", length=15)
    public String getClassrollno() {
        return this.classrollno;
    }
    
    public void setClassrollno(String classrollno) {
        this.classrollno = classrollno;
    }
    
    @Column(name="firstname", nullable=false, length=30)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="middlename", length=30)
    public String getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }
    
    @Column(name="lastname", nullable=false, length=30)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="idfather")
    public Integer getIdfather() {
        return this.idfather;
    }
    
    public void setIdfather(Integer idfather) {
        this.idfather = idfather;
    }
    
    @Column(name="idmother")
    public Integer getIdmother() {
        return this.idmother;
    }
    
    public void setIdmother(Integer idmother) {
        this.idmother = idmother;
    }
    
    @Column(name="idgd1")
    public Integer getIdgd1() {
        return this.idgd1;
    }
    
    public void setIdgd1(Integer idgd1) {
        this.idgd1 = idgd1;
    }
    
    @Column(name="idgd2")
    public Integer getIdgd2() {
        return this.idgd2;
    }
    
    public void setIdgd2(Integer idgd2) {
        this.idgd2 = idgd2;
    }
    
    @Column(name="idfeedivision", nullable=false)
    public int getIdfeedivision() {
        return this.idfeedivision;
    }
    
    public void setIdfeedivision(int idfeedivision) {
        this.idfeedivision = idfeedivision;
    }
    
    @Column(name="idfeediscountgp")
    public Integer getIdfeediscountgp() {
        return this.idfeediscountgp;
    }
    
    public void setIdfeediscountgp(Integer idfeediscountgp) {
        this.idfeediscountgp = idfeediscountgp;
    }
    
    @Column(name="idedusection")
    public Integer getIdedusection() {
        return this.idedusection;
    }
    
    public void setIdedusection(Integer idedusection) {
        this.idedusection = idedusection;
    }
    
    @Column(name="idedusemester")
    public Integer getIdedusemester() {
        return this.idedusemester;
    }
    
    public void setIdedusemester(Integer idedusemester) {
        this.idedusemester = idedusemester;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    
    @Column(name="pob", length=30)
    public String getPob() {
        return this.pob;
    }
    
    public void setPob(String pob) {
        this.pob = pob;
    }
    
    @Column(name="previousyearfeedues", precision=22, scale=0)
    public Double getPreviousyearfeedues() {
        return this.previousyearfeedues;
    }
    
    public void setPreviousyearfeedues(Double previousyearfeedues) {
        this.previousyearfeedues = previousyearfeedues;
    }
    
    @Column(name="previousschoolscholarno", length=15)
    public String getPreviousschoolscholarno() {
        return this.previousschoolscholarno;
    }
    
    public void setPreviousschoolscholarno(String previousschoolscholarno) {
        this.previousschoolscholarno = previousschoolscholarno;
    }
    
    @Column(name="previousschool", length=50)
    public String getPreviousschool() {
        return this.previousschool;
    }
    
    public void setPreviousschool(String previousschool) {
        this.previousschool = previousschool;
    }
    
    @Column(name="previousclass", length=20)
    public String getPreviousclass() {
        return this.previousclass;
    }
    
    public void setPreviousclass(String previousclass) {
        this.previousclass = previousclass;
    }
    
    @Column(name="previousresult", length=5)
    public String getPreviousresult() {
        return this.previousresult;
    }
    
    public void setPreviousresult(String previousresult) {
        this.previousresult = previousresult;
    }
    
    @Column(name="previousdivision", length=2)
    public String getPreviousdivision() {
        return this.previousdivision;
    }
    
    public void setPreviousdivision(String previousdivision) {
        this.previousdivision = previousdivision;
    }
    
    @Column(name="previouspercentage", precision=22, scale=0)
    public Double getPreviouspercentage() {
        return this.previouspercentage;
    }
    
    public void setPreviouspercentage(Double previouspercentage) {
        this.previouspercentage = previouspercentage;
    }
    
    @Column(name="reasonofleaving", length=50)
    public String getReasonofleaving() {
        return this.reasonofleaving;
    }
    
    public void setReasonofleaving(String reasonofleaving) {
        this.reasonofleaving = reasonofleaving;
    }
    
    @Column(name="idmothertongue")
    public Integer getIdmothertongue() {
        return this.idmothertongue;
    }
    
    public void setIdmothertongue(Integer idmothertongue) {
        this.idmothertongue = idmothertongue;
    }
    
    @Column(name="email", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="praddrhouseno", length=30)
    public String getPraddrhouseno() {
        return this.praddrhouseno;
    }
    
    public void setPraddrhouseno(String praddrhouseno) {
        this.praddrhouseno = praddrhouseno;
    }
    
    @Column(name="praddrstreet", length=30)
    public String getPraddrstreet() {
        return this.praddrstreet;
    }
    
    public void setPraddrstreet(String praddrstreet) {
        this.praddrstreet = praddrstreet;
    }
    
    @Column(name="praddrarea")
    public Integer getPraddrarea() {
        return this.praddrarea;
    }
    
    public void setPraddrarea(Integer praddrarea) {
        this.praddrarea = praddrarea;
    }
    
    @Column(name="praddrcity")
    public Integer getPraddrcity() {
        return this.praddrcity;
    }
    
    public void setPraddrcity(Integer praddrcity) {
        this.praddrcity = praddrcity;
    }
    
    @Column(name="praddrstate")
    public Integer getPraddrstate() {
        return this.praddrstate;
    }
    
    public void setPraddrstate(Integer praddrstate) {
        this.praddrstate = praddrstate;
    }
    
    @Column(name="praddrpin")
    public Integer getPraddrpin() {
        return this.praddrpin;
    }
    
    public void setPraddrpin(Integer praddrpin) {
        this.praddrpin = praddrpin;
    }
    
    @Column(name="pmaddrhouseno", length=30)
    public String getPmaddrhouseno() {
        return this.pmaddrhouseno;
    }
    
    public void setPmaddrhouseno(String pmaddrhouseno) {
        this.pmaddrhouseno = pmaddrhouseno;
    }
    
    @Column(name="pmaddrstreet", length=30)
    public String getPmaddrstreet() {
        return this.pmaddrstreet;
    }
    
    public void setPmaddrstreet(String pmaddrstreet) {
        this.pmaddrstreet = pmaddrstreet;
    }
    
    @Column(name="pmaddrarea")
    public Integer getPmaddrarea() {
        return this.pmaddrarea;
    }
    
    public void setPmaddrarea(Integer pmaddrarea) {
        this.pmaddrarea = pmaddrarea;
    }
    
    @Column(name="pmaddrcity")
    public Integer getPmaddrcity() {
        return this.pmaddrcity;
    }
    
    public void setPmaddrcity(Integer pmaddrcity) {
        this.pmaddrcity = pmaddrcity;
    }
    
    @Column(name="pmaddrstate")
    public Integer getPmaddrstate() {
        return this.pmaddrstate;
    }
    
    public void setPmaddrstate(Integer pmaddrstate) {
        this.pmaddrstate = pmaddrstate;
    }
    
    @Column(name="pmaddrpin")
    public Integer getPmaddrpin() {
        return this.pmaddrpin;
    }
    
    public void setPmaddrpin(Integer pmaddrpin) {
        this.pmaddrpin = pmaddrpin;
    }
    
    @Column(name="nationality", length=10)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    
    @Column(name="weight", precision=22, scale=0)
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    
    @Column(name="height", precision=22, scale=0)
    public Double getHeight() {
        return this.height;
    }
    
    public void setHeight(Double height) {
        this.height = height;
    }
    
    @Column(name="bloodgp", length=3)
    public String getBloodgp() {
        return this.bloodgp;
    }
    
    public void setBloodgp(String bloodgp) {
        this.bloodgp = bloodgp;
    }
    
    @Column(name="phydisab", length=30)
    public String getPhydisab() {
        return this.phydisab;
    }
    
    public void setPhydisab(String phydisab) {
        this.phydisab = phydisab;
    }
    
    @Column(name="idcategory")
    public Integer getIdcategory() {
        return this.idcategory;
    }
    
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }
    
    @Column(name="idreligion")
    public Integer getIdreligion() {
        return this.idreligion;
    }
    
    public void setIdreligion(Integer idreligion) {
        this.idreligion = idreligion;
    }
    
    @Column(name="idcaste")
    public Integer getIdcaste() {
        return this.idcaste;
    }
    
    public void setIdcaste(Integer idcaste) {
        this.idcaste = idcaste;
    }
    
    @Column(name="gender", nullable=false, length=6)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="nobrothers")
    public Integer getNobrothers() {
        return this.nobrothers;
    }
    
    public void setNobrothers(Integer nobrothers) {
        this.nobrothers = nobrothers;
    }
    
    @Column(name="nosisters")
    public Integer getNosisters() {
        return this.nosisters;
    }
    
    public void setNosisters(Integer nosisters) {
        this.nosisters = nosisters;
    }
    
    @Column(name="shift", length=8)
    public String getShift() {
        return this.shift;
    }
    
    public void setShift(String shift) {
        this.shift = shift;
    }
    
    @Column(name="idstaff", length=15)
    public String getIdstaff() {
        return this.idstaff;
    }
    
    public void setIdstaff(String idstaff) {
        this.idstaff = idstaff;
    }
    
    @Column(name="staffname", length=60)
    public String getStaffname() {
        return this.staffname;
    }
    
    public void setStaffname(String staffname) {
        this.staffname = staffname;
    }
    
    @Column(name="staffdesig", length=40)
    public String getStaffdesig() {
        return this.staffdesig;
    }
    
    public void setStaffdesig(String staffdesig) {
        this.staffdesig = staffdesig;
    }
    
    @Column(name="photo")
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    
    @Column(name="contactno")
    public Long getContactno() {
        return this.contactno;
    }
    
    public void setContactno(Long contactno) {
        this.contactno = contactno;
    }
    
    @Column(name="idhostelbed")
    public Integer getIdhostelbed() {
        return this.idhostelbed;
    }
    
    public void setIdhostelbed(Integer idhostelbed) {
        this.idhostelbed = idhostelbed;
    }
    
    @Column(name="idvehiclearea")
    public Integer getIdvehiclearea() {
        return this.idvehiclearea;
    }
    
    public void setIdvehiclearea(Integer idvehiclearea) {
        this.idvehiclearea = idvehiclearea;
    }
    
    @Column(name="deltag")
    public Integer getDeltag() {
        return this.deltag;
    }
    
    public void setDeltag(Integer deltag) {
        this.deltag = deltag;
    }
    
    @Column(name="idacademicsession")
    public Integer getIdacademicsession() {
        return this.idacademicsession;
    }
    
    public void setIdacademicsession(Integer idacademicsession) {
        this.idacademicsession = idacademicsession;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentByIdsibling3")
    public Set<Student> getStudentsForIdsibling3() {
        return this.studentsForIdsibling3;
    }
    
    public void setStudentsForIdsibling3(Set<Student> studentsForIdsibling3) {
        this.studentsForIdsibling3 = studentsForIdsibling3;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentByIdsibling1")
    public Set<Student> getStudentsForIdsibling1() {
        return this.studentsForIdsibling1;
    }
    
    public void setStudentsForIdsibling1(Set<Student> studentsForIdsibling1) {
        this.studentsForIdsibling1 = studentsForIdsibling1;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentByIdsibling2")
    public Set<Student> getStudentsForIdsibling2() {
        return this.studentsForIdsibling2;
    }
    
    public void setStudentsForIdsibling2(Set<Student> studentsForIdsibling2) {
        this.studentsForIdsibling2 = studentsForIdsibling2;
    }




}


